# Generated by Django 5.1.4 on 2025-01-08 19:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharefile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notes',
            new_name='NotesForm',
        ),
    ]
