# Generated by Django 5.1.4 on 2025-01-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharefile', '0002_rename_notes_notesform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesform',
            name='notefile',
            field=models.ImageField(upload_to='media'),
        ),
    ]
