# Generated by Django 5.1.4 on 2025-01-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharefile', '0004_remove_notesform_filetype_remove_notesform_notefile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesform',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
